"""add_event_owner

Revision ID: 746e63f72c9c
Revises: 7379e981e3af
Create Date: 2026-04-18 14:17:45.741837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746e63f72c9c'
down_revision: Union[str, Sequence[str], None] = '7379e981e3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_event_owner'), ['owner'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_owner'))
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
