"""add_tenant_id_and_usage_record

Revision ID: a69a255c8b8b
Revises: 746e63f72c9c
Create Date: 2026-04-19 07:56:27.481101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69a255c8b8b'
down_revision: Union[str, Sequence[str], None] = '746e63f72c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usagerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usagerecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usagerecord_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_event_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('usagerecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usagerecord_tenant_id'))

    op.drop_table('usagerecord')
    # ### end Alembic commands ###
