"""
Tests for the 8 G.O.D.A.I. ContextOS hard invariants.

Invariant 1: Register ↔ Log mutual dependency
Invariant 2: SSOT is immutable (INSERT only)
Invariant 3: WORK is mutable (PATCH allowed, DELETE not)
Invariant 4: No-Citation = No-Assertion
Invariant 5: All IDs generated by id_generator pass validate_id
Invariant 6: MNEMOSYNE is external only (godai_audit is the sole bridge)
Invariant 7: CommitBlocks are frozen (immutable after creation)
Invariant 8: ContextOS internal chain integrity verifiable at any time
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest

from contextos.commit import make_commit
from contextos.id_generator import generate_id, validate_id
from contextos.log import ContextOSLog, TamperDetectedError
from contextos.types import Actor, Citation, Cluster, CommitBlock, CommitOp, EntryType, Kind, TruthGate
from tests.contextos.conftest import make_mkid, make_nkid, make_ssot, make_work


# ── Invariant 1 ───────────────────────────────────────────────────────────────

def test_invariant_1_register_log_mutual_dependency(register, cos_log):
    """Every register write produces exactly one log entry."""
    nkid = make_nkid(0)
    before = len(cos_log)
    register.insert_ssot(make_ssot(nkid))
    assert len(cos_log) == before + 1


def test_invariant_1_log_always_matches_register(register, cos_log):
    """After N writes, log has exactly N entries."""
    for i in range(5):
        register.insert_ssot(make_ssot(make_nkid(i), f"content {i}"))
    assert len(cos_log) == 5


# ── Invariant 2 ───────────────────────────────────────────────────────────────

def test_invariant_2_ssot_immutable(register):
    """SSOT entries cannot be overwritten via insert_ssot."""
    nkid = make_nkid(10)
    register.insert_ssot(make_ssot(nkid, "original"))
    with pytest.raises(Exception):
        register.insert_ssot(make_ssot(nkid, "overwrite attempt"))


# ── Invariant 3 ───────────────────────────────────────────────────────────────

def test_invariant_3_work_is_mutable(register):
    """WORK entries can be patched (content updated)."""
    mkid = make_mkid(10)
    register.insert_work(make_work(mkid, "v1"))
    register.update_work(mkid, "v2", Actor.USER)
    w = register.get_work(mkid)
    assert w.content == "v2"


def test_invariant_3_promoted_work_cannot_be_patched(register):
    """A promoted WORK entry must not accept further patches."""
    mkid = make_mkid(11)
    nkid = make_nkid(11)
    register.insert_work(make_work(mkid))
    register.promote_work(mkid, nkid, Actor.USER)
    with pytest.raises(ValueError, match="promoted"):
        register.update_work(mkid, "sneaky patch", Actor.USER)


# ── Invariant 4 ───────────────────────────────────────────────────────────────

def test_invariant_4_no_citation_no_assertion_ssot(register):
    nkid = make_nkid(20)
    with pytest.raises(ValueError, match="No-Citation"):
        register.insert_ssot(make_ssot(nkid, truth_gate=TruthGate.CORROBORATED, citations=()))


def test_invariant_4_empty_but_verified_needs_no_citation(register):
    """EMPTY_BUT_VERIFIED is exempted from the citation requirement."""
    nkid = make_nkid(21)
    register.insert_ssot(make_ssot(nkid, truth_gate=TruthGate.EMPTY_BUT_VERIFIED, citations=()))
    assert register.get_ssot(nkid) is not None


# ── Invariant 5 ───────────────────────────────────────────────────────────────

def test_invariant_5_generated_ids_always_valid():
    for i in range(20):
        id_str = generate_id(
            Kind.NK, Actor.USER, Cluster.GENERAL, EntryType.FACT,
            TruthGate.UNVERIFIED, time_bucket="0A", sequence=i,
        )
        assert validate_id(id_str), f"Invalid ID at sequence {i}: {id_str}"


# ── Invariant 6 ───────────────────────────────────────────────────────────────

def test_invariant_6_godai_import_only_in_bridge():
    """Only godai_audit.py should import from godai; no other contextos module should."""
    import importlib
    import sys

    # Modules that must NOT import godai directly
    forbidden_modules = [
        "contextos.types",
        "contextos.id_generator",
        "contextos.store",
        "contextos.log",
        "contextos.commit",
        "contextos.register",
        "contextos.index",
        "contextos.resolver",
        "contextos.mkid_runner",
        "contextos.ui",
    ]
    for mod_name in forbidden_modules:
        mod = importlib.import_module(mod_name)
        src = getattr(mod, "__file__", "") or ""
        if src:
            import ast
            with open(src) as f:
                tree = ast.parse(f.read())
            for node in ast.walk(tree):
                if isinstance(node, (ast.Import, ast.ImportFrom)):
                    names = (
                        [node.module or ""] if isinstance(node, ast.ImportFrom)
                        else [alias.name for alias in node.names]
                    )
                    for name in names:
                        assert not (name or "").startswith("godai"), (
                            f"{mod_name} illegally imports godai: {name}"
                        )


# ── Invariant 7 ───────────────────────────────────────────────────────────────

def test_invariant_7_commitblock_frozen():
    cb = make_commit(CommitOp.PATCH, "NK00000000000000", Actor.USER, "a" * 64)
    with pytest.raises(Exception):
        cb.operation = CommitOp.DEPRECATE  # type: ignore[misc]


# ── Invariant 8 ───────────────────────────────────────────────────────────────

def test_invariant_8_chain_integrity_after_multiple_writes(register, cos_log):
    for i in range(10):
        register.insert_ssot(make_ssot(make_nkid(i), f"entry {i}"))
    assert cos_log.verify_chain() is True
